name: backend-main-ci
on:
  push:
    paths:
    - 'backend-main/**'
defaults:
  run:
    working-directory: backend-main
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - name: build 
      uses: docker/build-push-action@v1
      with:
        path: ../../backend-main
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: eu.gcr.io
        repository: digger-boot-267123/dg-myapp-backend-main
        tags: latest
